#spring:
#  application:
#    name: Zuul-gateway
#eureka:
#  client:
##    serviceUrl:
##      defaultZone: ${EUREKA_URI:http://172.17.0.1:8761/eureka/}
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#server:
#  port: 8080
#
##Zuul
#zuul:
#  routes:
#    two-api:
#      path: "/two-api/**"
#      url: "http://localhost:9090/"
#      stripPrefix: false